#!/bin/bash

set -u

rsync -avh --delete \
--exclude=.git \
--exclude=.nodecg \
--exclude=bundle-analyzer \
--exclude=node_modules \
--exclude=src \
--exclude=webpack-templates \
. restream:~/nodecg

ssh restream ". .nvm/nvm.sh && cd nodecg && yarn install --prod"
